import '../App.css';
const styles = {
    App:{
        width:"100%",
        overflow: "hidden",
    },
    home:{
        width:"100%",
        height:"100%",
        display:"flex",
        alignItems:"center",
        justifyContent:"center"
    },
    homeHeading:{
        color:"#00A8CC",
        fontFamily:"LeagueSpartan",
        fontSize:"70px",
        margin:0
    },
    textColor:{
        color:"#00A8CC"
    },
    experiencePage:{
        display:"flex",
        justifyContent:"space-around",
        flexWrap:"wrap"
    },
    heading:{
        marginBottom:"0",
        color:"#00A8CC",
        fontFamily:"Aileron",
        fontSize:"40px"
    },
    dividerContainer:{
        marginTop:"15px",
        marginBottom:"30px",
        display:"flex",
        justifyContent:"center",
        padding:'0'
    },
    divider:{
        borderBottomWidth:"3px",
        backgroundColor:"#00A8CC",
        width:"150px"
    },
    languagesContainer:{
        marginLeft:"50px",
        fontSize:"18px"
    },
    languages:{
        display:"flex",
        flexDirection:"column",
        gap:"0px 30px",
        textAlign:"left",
        listStylePosition: 'inside',
        color:"#00A8CC",
        width:"100%",
        padding:"0",
        margin:"0"
    },
    bold:{
        fontWeight:"bold"
    },
    work:{
        color:"#00A8CC",
        listStylePosition: 'inside',
        textAlign:"left",
        fontSize:"18px"
    },
    contactContainer:{
        width:"100%",
        display:"flex",
        alignItems:"center",
        backgroundColor:"#27496D",
        height:"100%",
        overflow:"hidden"
    },
    contact:{
        display:"flex",
        justifyContent:'center',
        width:"100%",
        gap:"20px"
    },
    contactIconButton:{
        borderRadius:"50%", 
        backgroundColor:"#00A8CC"
    },
    contactIcon:{
        color:"#142850",
        fontSize:"25px"
    },
    toolBar:{
        display:"flex",
        justifyContent:"flex-end",
        gap:"50px",
    },
    projects:{
        height:'100%',
        display:"flex",
        flexDirection:"column",
        justifyContent:"center"
    },
    linkText:{
        textDecoration:"none",
        color:"#004ead"
    },
    centeredText:{
        color:"#00A8CC",
        textAlign:"center"
    },
    dialogTitle:{
        fontSize:"25px",
        textAlign:"center",
        textDecoration: "underline",
        textDecorationWidth:"3px",
        fontFamily:"Aileron"
    },
    dialogContent:{
        display:'flex',
    },
    dialogImageButtons:{
        marginLeft:"-100%",
        top:"219px",
        display:"flex",
        justifyContent:"space-between",
        width:"100%"
    },
    forwardImageButton:{
        display:"flex",
        justifyContent:"flex-end",
        width:"100%"
    },
    dialogMadeWith:{
        color:"#00A8CC",
        fontStyle:"italic",
        fontWeight:"bold",
        marginLeft:"10px"
    },
    dialogTextContainer:{
        width:"100%",
        display:"flex",
        justifyContent:"center",
        padding:"0",
        margin:"0"
    },
    dialogText:{
        color:"#00A8CC", 
        width:"75%", 
        whiteSpace: "pre-line",
        textAlign:"center",
        padding:"0",
        margin:"0"
    },
    dialogIconsContainer:{
        display:"flex",
        justifyContent:"center",
        margin:"10px",
        gap:"5px"
    },
    clickableImage:{
        cursor:"pointer"
    },
    notFocusedImage:{
        opacity: "0.4"
    },
    imageContainerButtons:{
        display:"flex",
        justifyContent:"space-between",
        width:"710px"
    },
    selectedImageSlider:{
        width:"100%",
        display:"flex",
        justifyContent:"center",
        gap:"10px",
        marginTop:"5px"
    },
    imageSliderIcon:{
        fontSize:"12px"
    },
    aboutImage:{
        width:"200px",
        height:"200px",
        border:"3px #00A8CC solid",
        borderRadius: "50%"
    },
    aboutTextContainer:{
        color:"#00A8CC",
        display:'flex',
        flexDirection:"column",
        gap:"10px",
        fontSize:"18px"
    },
    aboutBigText:{
        fontSize:"22px"
    }
}
export default styles;